-- MySQL Script generated by MySQL Workbench
-- Thu Dec 10 00:56:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskforce` DEFAULT CHARACTER SET utf8 ;
USE `taskforce` ;

-- -----------------------------------------------------
-- Table `taskforce`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`users` (
  `id` INT(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `city_id` INT(10) NULL,
  `password` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `role` ENUM('employer', 'implementer') NOT NULL,
  `birthday` VARCHAR(10) NULL,
  `phone` VARCHAR(15) NULL,
  `skype` VARCHAR(45) NULL,
  `telegram` VARCHAR(45) NULL,
  `last_visit` DATETIME NOT NULL,
  `avatar_url` VARCHAR(255) NULL,
  `date_create` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `name` (`name` ASC),
  INDEX `city_id_idx` (`city_id` ASC),
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `taskforce`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(15) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `price` INT NULL,
  `status` ENUM('new', 'in_work', 'done', 'failed', 'cancel') NOT NULL DEFAULT 'new',
  `location` VARCHAR(100) NULL,
  `deadline` DATE NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `date_create_idx` (`date_create` ASC),
  INDEX `title_idx` (`title` ASC),
  INDEX `status` (`status` ASC),
  INDEX `category_id_task` (`category_id` ASC),
  CONSTRAINT `user_id_task`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id_task`
    FOREIGN KEY (`category_id`)
    REFERENCES `taskforce`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `rating` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task_id_idx` (`task_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `task_id_feed`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_feed`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`photo_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`photo_work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `url_photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_photo` (`user_id` ASC),
  CONSTRAINT `user_id_p`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`files_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`files_task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `url_file` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `last_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task_user_idx` (`user_id` ASC),
  INDEX `task_id_r` (`task_id` ASC),
  CONSTRAINT `task_id_r`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_user_r`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `text` LONGTEXT NOT NULL,
  `last_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task_id_idx` (`task_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `task_id_ch`
    FOREIGN KEY (`task_id`)
    REFERENCES `taskforce`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_ch`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `html_form` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`recipient_id` ASC),
  INDEX `event_id_idx` (`event_id` ASC),
  CONSTRAINT `user_id_not`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `taskforce`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`favourites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`favourites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `favourite_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `favorit_id_idx` (`favourite_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `favorit_id_fav`
    FOREIGN KEY (`favourite_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fav`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`user_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`user_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`category_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `category_id_uc`
    FOREIGN KEY (`category_id`)
    REFERENCES `taskforce`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_uc`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`value_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`value_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taskforce`.`selected_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`selected_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value_name_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `value_name_id_idx` (`value_name_id` ASC),
  INDEX `user_id_sn_idx` (`user_id` ASC),
  CONSTRAINT `value_name_id`
    FOREIGN KEY (`value_name_id`)
    REFERENCES `taskforce`.`value_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_sn`
    FOREIGN KEY (`user_id`)
    REFERENCES `taskforce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
